/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AlarmReport: typeof import('./src/components/rightChartComponents/alarmReport.vue')['default']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ChartTitle: typeof import('./src/components/chartTitle.vue')['default']
    DevStatus: typeof import('./src/components/rightChartComponents/devStatus.vue')['default']
    ElectricityRank: typeof import('./src/components/bottomChartComponents/electricityRank.vue')['default']
    MapContainer: typeof import('./src/components/mapContainer.vue')['default']
    OperationManage: typeof import('./src/components/bottomChartComponents/operationManage.vue')['default']
    PowerStationCapacity: typeof import('./src/components/bottomChartComponents/powerStationCapacity.vue')['default']
    RealTime: typeof import('./src/components/bottomChartComponents/realTime.vue')['default']
    RealTimePower: typeof import('./src/components/bottomChartComponents/RealTimePower.vue')['default']
    RPefficiency: typeof import('./src/components/bottomChartComponents/RPefficiency.vue')['default']
    ScaleBox: typeof import('./src/components/scaleBox.vue')['default']
    SocialContribution: typeof import('./src/components/leftChartComponents/socialContribution.vue')['default']
    StationHealthy: typeof import('./src/components/leftChartComponents/stationHealthy.vue')['default']
  }
}
